"""Add flow execution models

Revision ID: 082db8e1d450
Revises: e1ad8d3751a4
Create Date: 2025-11-14 17:20:07.306508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '082db8e1d450'
down_revision = 'e1ad8d3751a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_stage_id', sa.Integer(), nullable=True),
    sa.Column('current_assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'TERMINATED', 'STALLED', name='flowstatus'), nullable=False),
    sa.Column('initiated_by_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['flow_template_id'], ['flow_templates.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_instances_id'), 'flow_instances', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_instance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('FLOW_STARTED', 'STAGE_COMPLETED', 'STAGE_APPROVED', 'STAGE_REJECTED', 'TASK_REASSIGNED', 'TASK_DELEGATED', 'COMMENT_ADDED', 'FLOW_COMPLETED', 'FLOW_TERMINATED', name='activitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flow_instance_id'], ['flow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_flow_instance_id'), 'activity_logs', ['flow_instance_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('task_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_instance_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='taskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('completion_action', sa.Enum('COMPLETE', 'APPROVE', 'REQUEST_CHANGES', 'DELEGATE', name='completionaction'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flow_instance_id'], ['flow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_instances_assignee_id'), 'task_instances', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_task_instances_id'), 'task_instances', ['id'], unique=False)
    op.create_index(op.f('ix_task_instances_status'), 'task_instances', ['status'], unique=False)
    op.create_table('form_data_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_instance_id', sa.Integer(), nullable=False),
    sa.Column('form_field_id', sa.Integer(), nullable=False),
    sa.Column('task_instance_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flow_instance_id'], ['flow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_data_values_id'), 'form_data_values', ['id'], unique=False)
    op.drop_column('stages', 'position_y')
    op.drop_column('stages', 'position_x')
    op.drop_column('stages', 'node_type')
    op.drop_column('stages', 'next_stage_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('next_stage_ids', sqlite.JSON(), nullable=True))
    op.add_column('stages', sa.Column('node_type', sa.VARCHAR(), nullable=True))
    op.add_column('stages', sa.Column('position_x', sa.INTEGER(), nullable=True))
    op.add_column('stages', sa.Column('position_y', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_form_data_values_id'), table_name='form_data_values')
    op.drop_table('form_data_values')
    op.drop_index(op.f('ix_task_instances_status'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_assignee_id'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_flow_instance_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_flow_instances_id'), table_name='flow_instances')
    op.drop_table('flow_instances')
    # ### end Alembic commands ###
